# files_in    = '$ICDIR/database/test_data/electrons_40keV_z25_RWF.h5'
# file_out    = '/tmp/electrons_40keV_z25_sipmPDF.h5'
files_in    = '/home/investigator/Documents/HD_Demo/analysis/data/test/Run573/run_573_0000_ldc1_trg0.waveforms.h5'
file_out    = '/home/investigator/Documents/HD_Demo/analysis/data/test/run_573_0000_ldc1_trg0_trude.waveforms.h5'
compression = 'ZLIB4'
print_mod   = 1
event_range = 100

run_number    = 573
detector_db   = 'hddemo'

# Histogram bins
min_bin   = - 49.5
max_bin   =  200.5
bin_width =    1


proc_mode        = subtract_mode
number_integrals =     1
integral_start   =    41
integral_width   =     2
integrals_period =    50
